var searchData=
[
  ['object_20labeling_201282_0',['Object Labeling (1282)',['../md_docs_2opengl__cleanup.html#autotoc_md156',1,'']]],
  ['object_20labeling_20initialization_20sequence_20error_201282_1',['2. Object Labeling &amp; Initialization Sequence (Error 1282)',['../md_docs_2nvidia__optimizations.html#autotoc_md147',1,'']]],
  ['of_20nolint_2',['Why use this instead of // NOLINT?',['../md_docs_2raii__cleanup__guide.html#autotoc_md279',1,'']]],
  ['offline_3',['2. Building (Offline)',['../md_docs_2build.html#autotoc_md25',1,'']]],
  ['offline_20build_20support_4',['Offline Build Support',['../md_docs_2build.html#autotoc_md23',1,'']]],
  ['offline_20mode_5',['3. Testing the Offline Mode',['../md_docs_2build.html#autotoc_md26',1,'']]],
  ['offs_6',['Trade-offs',['../md_docs_2gpu-rendering-synchronization.html#autotoc_md116',1,'']]],
  ['offset_7',['offset',['../structColorGradingParams.html#aef2056f6ab8806d8afcb039f6aad33f9',1,'ColorGradingParams']]],
  ['ogl_8',['Suckless-OGL',['../index.html',1,'']]],
  ['on_20debian_2013_9',['1. Installation on Debian 13',['../md_docs_2renderdoc__guide.html#autotoc_md286',1,'']]],
  ['on_20debian_2013_20intel_20iris_20xe_10',['User Guide: RenderDoc on Debian 13 (Intel Iris Xe)',['../md_docs_2renderdoc__guide.html',1,'']]],
  ['on_20derivative_20precision_11',['1. Avoid Relying on Derivative Precision',['../md_docs_2shader-cross-gpu-compatibility.html#autotoc_md294',1,'']]],
  ['online_12',['1. Preparation (Online)',['../md_docs_2build.html#autotoc_md24',1,'']]],
  ['opengl_20loader_20generator_13',['GLAD (OpenGL Loader Generator)',['../md_docs_2build.html#autotoc_md29',1,'']]],
  ['opengl_20mathematics_20for_20c_14',['cglm (OpenGL Mathematics for C)',['../md_docs_2build.html#autotoc_md28',1,'']]],
  ['opengl_20stability_20performance_20cleanup_202026_2001_2028_15',['OpenGL Stability &amp; Performance Cleanup (2026-01-28)',['../md_docs_2opengl__cleanup.html',1,'']]],
  ['opengl_20support_3a_20launch_20stability_20optimizations_16',['NVIDIA OpenGL Support: Launch, Stability &amp; Optimizations',['../md_docs_2nvidia__optimizations.html',1,'']]],
  ['opengl_5fcleanup_2emd_17',['opengl_cleanup.md',['../opengl__cleanup_8md.html',1,'']]],
  ['optimization_18',['optimization',['../md_docs_2FXAA.html#autotoc_md102',1,'1. Luma-in-Alpha (Bandwidth Optimization)'],['../md_docs_2docker.html#autotoc_md56',1,'Build Cache Optimization'],['../md_docs_2skybox__rendering.html#autotoc_md319',1,'Early-Z Optimization'],['../md_docs_2shader__optimization.html',1,'Post-Processing Shader Optimization']]],
  ['optimization_20diagram_19',['Optimization Diagram',['../md_docs_2skybox__rendering.html#autotoc_md320',1,'']]],
  ['optimization_20immutable_20storage_20',['Texture Pipeline Optimization (Immutable Storage)',['../md_docs_2texture__optimization.html',1,'']]],
  ['optimization_20strategies_21',['IBL Optimization Strategies',['../md_docs_2ibl__architecture__ideas.html',1,'']]],
  ['optimizations_22',['optimizations',['../md_docs_2exposure__analysis.html#autotoc_md96',1,'4. Pre-calculation and Optimizations'],['../md_docs_2FXAA.html',1,'FXAA 3.11 Implementation &amp; Optimizations'],['../md_docs_2FXAA.html#autotoc_md101',1,'Key Optimizations'],['../md_docs_2nvidia__optimizations.html',1,'NVIDIA OpenGL Support: Launch, Stability &amp; Optimizations']]],
  ['optimizations_20nvidia_23',['2. Performance Optimizations (NVIDIA)',['../md_docs_2opengl__cleanup.html#autotoc_md158',1,'']]],
  ['optimized_20configuration_20adaptive_20slicing_24',['3. Optimized Configuration (Adaptive Slicing)',['../md_docs_2progressive__ibl.html#autotoc_md233',1,'']]],
  ['organization_25',['✅ Organization',['../md_docs_2project__structure.html#autotoc_md248',1,'']]],
  ['orientation_20correction_26',['Orientation Correction',['../md_docs_2skybox__rendering.html#autotoc_md324',1,'']]],
  ['origin_27',['Photographic Origin',['../md_docs_2photographic__standards.html#autotoc_md166',1,'']]],
  ['original_20code_28',['Improvements over Original Code',['../md_docs_2project__structure.html#autotoc_md247',1,'']]],
  ['original_5findex_29',['original_index',['../structSphereSortEntry.html#aed13255308b43481740f760886695969',1,'SphereSortEntry']]],
  ['orthonormalbasis_30',['OrthonormalBasis',['../irmap_8glsl.html#a9484186418ffa087e49afbe7f07b5920',1,'irmap.glsl']]],
  ['over_20original_20code_31',['Improvements over Original Code',['../md_docs_2project__structure.html#autotoc_md247',1,'']]],
  ['overlap_20protection_20crucial_32',['2.1 Overlap Protection (Crucial)',['../md_docs_2progressive__ibl.html#autotoc_md231',1,'']]],
  ['overview_33',['overview',['../md_docs_2postprocess__ubo__architecture.html#autotoc_md200',1,'1. Overview'],['../md_docs_2progressive__ibl.html#autotoc_md227',1,'1. Overview'],['../md_docs_2mouse__camera__control.html#autotoc_md135',1,'Overview'],['../md_docs_2FXAA.html#autotoc_md100',1,'Overview'],['../md_docs_2async__loader.html#autotoc_md16',1,'Overview'],['../md_docs_2shader-cross-gpu-compatibility.html#autotoc_md292',1,'Overview'],['../md_docs_2shader__optimization.html#autotoc_md309',1,'Overview'],['../md_docs_2architecture.html#autotoc_md9',1,'Overview']]],
  ['ownership_34',['Data Ownership',['../md_docs_2architecture.html#autotoc_md12',1,'']]]
];
