var searchData=
[
  ['object_20labeling_201282_0',['Object Labeling (1282)',['../md_docs_2opengl__cleanup.html#autotoc_md178',1,'']]],
  ['object_20labeling_20initialization_20sequence_20error_201282_1',['2. Object Labeling &amp; Initialization Sequence (Error 1282)',['../md_docs_2nvidia__optimizations.html#autotoc_md169',1,'']]],
  ['obtain_20a_20surge_20token_2',['1. Obtain a Surge Token',['../md_docs_2docs__staging__guide.html#autotoc_md85',1,'']]],
  ['of_20nolint_3',['Why use this instead of // NOLINT?',['../md_docs_2raii__cleanup__guide.html#autotoc_md302',1,'']]],
  ['offline_4',['2. Building (Offline)',['../md_docs_2build.html#autotoc_md38',1,'']]],
  ['offline_20build_20support_5',['Offline Build Support',['../md_docs_2build.html#autotoc_md36',1,'']]],
  ['offline_20mode_6',['3. Testing the Offline Mode',['../md_docs_2build.html#autotoc_md39',1,'']]],
  ['offs_7',['Trade-offs',['../md_docs_2gpu-rendering-synchronization.html#autotoc_md138',1,'']]],
  ['offset_8',['offset',['../structColorGradingParams.html#aef2056f6ab8806d8afcb039f6aad33f9',1,'ColorGradingParams']]],
  ['ogl_9',['Suckless-OGL',['../index.html',1,'']]],
  ['on_20debian_2013_10',['1. Installation on Debian 13',['../md_docs_2renderdoc__guide.html#autotoc_md309',1,'']]],
  ['on_20debian_2013_20intel_20iris_20xe_11',['User Guide: RenderDoc on Debian 13 (Intel Iris Xe)',['../md_docs_2renderdoc__guide.html',1,'']]],
  ['on_20derivative_20precision_12',['1. Avoid Relying on Derivative Precision',['../md_docs_2shader-cross-gpu-compatibility.html#autotoc_md317',1,'']]],
  ['online_13',['1. Preparation (Online)',['../md_docs_2build.html#autotoc_md37',1,'']]],
  ['opengl_20loader_20generator_14',['GLAD (OpenGL Loader Generator)',['../md_docs_2build.html#autotoc_md42',1,'']]],
  ['opengl_20mathematics_20for_20c_15',['cglm (OpenGL Mathematics for C)',['../md_docs_2build.html#autotoc_md41',1,'']]],
  ['opengl_20stability_20performance_20cleanup_202026_2001_2028_16',['OpenGL Stability &amp; Performance Cleanup (2026-01-28)',['../md_docs_2opengl__cleanup.html',1,'']]],
  ['opengl_20support_3a_20launch_20stability_20optimizations_17',['NVIDIA OpenGL Support: Launch, Stability &amp; Optimizations',['../md_docs_2nvidia__optimizations.html',1,'']]],
  ['opengl_5fcleanup_2emd_18',['opengl_cleanup.md',['../opengl__cleanup_8md.html',1,'']]],
  ['optimization_19',['optimization',['../md_docs_2FXAA.html#autotoc_md124',1,'1. Luma-in-Alpha (Bandwidth Optimization)'],['../md_docs_2docker.html#autotoc_md69',1,'Build Cache Optimization'],['../md_docs_2skybox__rendering.html#autotoc_md342',1,'Early-Z Optimization'],['../md_docs_2shader__optimization.html',1,'Post-Processing Shader Optimization']]],
  ['optimization_20diagram_20',['Optimization Diagram',['../md_docs_2skybox__rendering.html#autotoc_md343',1,'']]],
  ['optimization_20immutable_20storage_21',['Texture Pipeline Optimization (Immutable Storage)',['../md_docs_2texture__optimization.html',1,'']]],
  ['optimization_20strategies_22',['IBL Optimization Strategies',['../md_docs_2ibl__architecture__ideas.html',1,'']]],
  ['optimizations_23',['optimizations',['../md_docs_2exposure__analysis.html#autotoc_md118',1,'4. Pre-calculation and Optimizations'],['../md_docs_2FXAA.html',1,'FXAA 3.11 Implementation &amp; Optimizations'],['../md_docs_2FXAA.html#autotoc_md123',1,'Key Optimizations'],['../md_docs_2nvidia__optimizations.html',1,'NVIDIA OpenGL Support: Launch, Stability &amp; Optimizations']]],
  ['optimizations_20nvidia_24',['2. Performance Optimizations (NVIDIA)',['../md_docs_2opengl__cleanup.html#autotoc_md180',1,'']]],
  ['optimized_20configuration_20adaptive_20slicing_25',['3. Optimized Configuration (Adaptive Slicing)',['../md_docs_2progressive__ibl.html#autotoc_md255',1,'']]],
  ['organization_26',['✅ Organization',['../md_docs_2project__structure.html#autotoc_md270',1,'']]],
  ['orientation_20correction_27',['Orientation Correction',['../md_docs_2skybox__rendering.html#autotoc_md347',1,'']]],
  ['origin_28',['Photographic Origin',['../md_docs_2photographic__standards.html#autotoc_md188',1,'']]],
  ['original_20code_29',['Improvements over Original Code',['../md_docs_2project__structure.html#autotoc_md269',1,'']]],
  ['original_5findex_30',['original_index',['../structSphereSortEntry.html#aed13255308b43481740f760886695969',1,'SphereSortEntry']]],
  ['orthonormalbasis_31',['OrthonormalBasis',['../irmap_8glsl.html#a9484186418ffa087e49afbe7f07b5920',1,'irmap.glsl']]],
  ['over_20original_20code_32',['Improvements over Original Code',['../md_docs_2project__structure.html#autotoc_md269',1,'']]],
  ['overlap_20protection_20crucial_33',['2.1 Overlap Protection (Crucial)',['../md_docs_2progressive__ibl.html#autotoc_md253',1,'']]],
  ['overview_34',['overview',['../md_docs_2progressive__ibl.html#autotoc_md249',1,'1. Overview'],['../md_docs_2postprocess__ubo__architecture.html#autotoc_md222',1,'1. Overview'],['../md_docs_2architecture.html#autotoc_md9',1,'Overview'],['../md_docs_2shader-cross-gpu-compatibility.html#autotoc_md315',1,'Overview'],['../md_docs_2shader__optimization.html#autotoc_md332',1,'Overview'],['../md_docs_2async__loader.html#autotoc_md16',1,'Overview'],['../md_docs_2mouse__camera__control.html#autotoc_md157',1,'Overview'],['../md_docs_2FXAA.html#autotoc_md122',1,'Overview']]],
  ['ownership_35',['Data Ownership',['../md_docs_2architecture.html#autotoc_md12',1,'']]]
];
