# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /app

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /app

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /app/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"library\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /app/CMakeFiles /app//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /app/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /app/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named app

# Build rule for target.
app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 app
.PHONY : app

# fast build rule for target.
app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/build
.PHONY : app/fast

#=============================================================================
# Target rules for targets named cglm

# Build rule for target.
cglm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cglm
.PHONY : cglm

# fast build rule for target.
cglm/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cglm-build/CMakeFiles/cglm.dir/build.make _deps/cglm-build/CMakeFiles/cglm.dir/build
.PHONY : cglm/fast

#=============================================================================
# Target rules for targets named glad-generate-files

# Build rule for target.
glad-generate-files: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad-generate-files
.PHONY : glad-generate-files

# fast build rule for target.
glad-generate-files/fast:
	$(MAKE) $(MAKESILENT) -f _deps/glad-build/CMakeFiles/glad-generate-files.dir/build.make _deps/glad-build/CMakeFiles/glad-generate-files.dir/build
.PHONY : glad-generate-files/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f _deps/glad-build/CMakeFiles/glad.dir/build.make _deps/glad-build/CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f _deps/glfw-build/src/CMakeFiles/update_mappings.dir/build.make _deps/glfw-build/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f _deps/glfw-build/src/CMakeFiles/glfw.dir/build.make _deps/glfw-build/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named cjson

# Build rule for target.
cjson: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cjson
.PHONY : cjson

# fast build rule for target.
cjson/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cjson-build/CMakeFiles/cjson.dir/build.make _deps/cjson-build/CMakeFiles/cjson.dir/build
.PHONY : cjson/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f _deps/cjson-build/CMakeFiles/uninstall.dir/build.make _deps/cjson-build/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named unity

# Build rule for target.
unity: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 unity
.PHONY : unity

# fast build rule for target.
unity/fast:
	$(MAKE) $(MAKESILENT) -f _deps/unity-build/CMakeFiles/unity.dir/build.make _deps/unity-build/CMakeFiles/unity.dir/build
.PHONY : unity/fast

#=============================================================================
# Target rules for targets named app_testlib

# Build rule for target.
app_testlib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 app_testlib
.PHONY : app_testlib

# fast build rule for target.
app_testlib/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/app_testlib.dir/build.make tests/CMakeFiles/app_testlib.dir/build
.PHONY : app_testlib/fast

#=============================================================================
# Target rules for targets named test_adaptive_sampler_frames

# Build rule for target.
test_adaptive_sampler_frames: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_adaptive_sampler_frames
.PHONY : test_adaptive_sampler_frames

# fast build rule for target.
test_adaptive_sampler_frames/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_adaptive_sampler_frames.dir/build.make tests/CMakeFiles/test_adaptive_sampler_frames.dir/build
.PHONY : test_adaptive_sampler_frames/fast

#=============================================================================
# Target rules for targets named test_app

# Build rule for target.
test_app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_app
.PHONY : test_app

# fast build rule for target.
test_app/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_app.dir/build.make tests/CMakeFiles/test_app.dir/build
.PHONY : test_app/fast

#=============================================================================
# Target rules for targets named test_app_input

# Build rule for target.
test_app_input: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_app_input
.PHONY : test_app_input

# fast build rule for target.
test_app_input/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_app_input.dir/build.make tests/CMakeFiles/test_app_input.dir/build
.PHONY : test_app_input/fast

#=============================================================================
# Target rules for targets named test_app_metrics

# Build rule for target.
test_app_metrics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_app_metrics
.PHONY : test_app_metrics

# fast build rule for target.
test_app_metrics/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_app_metrics.dir/build.make tests/CMakeFiles/test_app_metrics.dir/build
.PHONY : test_app_metrics/fast

#=============================================================================
# Target rules for targets named test_async_loader_perf

# Build rule for target.
test_async_loader_perf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_async_loader_perf
.PHONY : test_async_loader_perf

# fast build rule for target.
test_async_loader_perf/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_async_loader_perf.dir/build.make tests/CMakeFiles/test_async_loader_perf.dir/build
.PHONY : test_async_loader_perf/fast

#=============================================================================
# Target rules for targets named test_benchmark_adaptive_sampler

# Build rule for target.
test_benchmark_adaptive_sampler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_benchmark_adaptive_sampler
.PHONY : test_benchmark_adaptive_sampler

# fast build rule for target.
test_benchmark_adaptive_sampler/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_benchmark_adaptive_sampler.dir/build.make tests/CMakeFiles/test_benchmark_adaptive_sampler.dir/build
.PHONY : test_benchmark_adaptive_sampler/fast

#=============================================================================
# Target rules for targets named test_benchmark_bloom

# Build rule for target.
test_benchmark_bloom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_benchmark_bloom
.PHONY : test_benchmark_bloom

# fast build rule for target.
test_benchmark_bloom/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_benchmark_bloom.dir/build.make tests/CMakeFiles/test_benchmark_bloom.dir/build
.PHONY : test_benchmark_bloom/fast

#=============================================================================
# Target rules for targets named test_benchmark_histogram

# Build rule for target.
test_benchmark_histogram: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_benchmark_histogram
.PHONY : test_benchmark_histogram

# fast build rule for target.
test_benchmark_histogram/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_benchmark_histogram.dir/build.make tests/CMakeFiles/test_benchmark_histogram.dir/build
.PHONY : test_benchmark_histogram/fast

#=============================================================================
# Target rules for targets named test_camera

# Build rule for target.
test_camera: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_camera
.PHONY : test_camera

# fast build rule for target.
test_camera/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_camera.dir/build.make tests/CMakeFiles/test_camera.dir/build
.PHONY : test_camera/fast

#=============================================================================
# Target rules for targets named test_cli

# Build rule for target.
test_cli: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_cli
.PHONY : test_cli

# fast build rule for target.
test_cli/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_cli.dir/build.make tests/CMakeFiles/test_cli.dir/build
.PHONY : test_cli/fast

#=============================================================================
# Target rules for targets named test_fps

# Build rule for target.
test_fps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_fps
.PHONY : test_fps

# fast build rule for target.
test_fps/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_fps.dir/build.make tests/CMakeFiles/test_fps.dir/build
.PHONY : test_fps/fast

#=============================================================================
# Target rules for targets named test_fxaa_synthetic

# Build rule for target.
test_fxaa_synthetic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_fxaa_synthetic
.PHONY : test_fxaa_synthetic

# fast build rule for target.
test_fxaa_synthetic/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_fxaa_synthetic.dir/build.make tests/CMakeFiles/test_fxaa_synthetic.dir/build
.PHONY : test_fxaa_synthetic/fast

#=============================================================================
# Target rules for targets named test_gpu_profiler

# Build rule for target.
test_gpu_profiler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_gpu_profiler
.PHONY : test_gpu_profiler

# fast build rule for target.
test_gpu_profiler/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_gpu_profiler.dir/build.make tests/CMakeFiles/test_gpu_profiler.dir/build
.PHONY : test_gpu_profiler/fast

#=============================================================================
# Target rules for targets named test_icosphere

# Build rule for target.
test_icosphere: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_icosphere
.PHONY : test_icosphere

# fast build rule for target.
test_icosphere/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_icosphere.dir/build.make tests/CMakeFiles/test_icosphere.dir/build
.PHONY : test_icosphere/fast

#=============================================================================
# Target rules for targets named test_instanced_rendering

# Build rule for target.
test_instanced_rendering: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_instanced_rendering
.PHONY : test_instanced_rendering

# fast build rule for target.
test_instanced_rendering/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_instanced_rendering.dir/build.make tests/CMakeFiles/test_instanced_rendering.dir/build
.PHONY : test_instanced_rendering/fast

#=============================================================================
# Target rules for targets named test_log

# Build rule for target.
test_log: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_log
.PHONY : test_log

# fast build rule for target.
test_log/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_log.dir/build.make tests/CMakeFiles/test_log.dir/build
.PHONY : test_log/fast

#=============================================================================
# Target rules for targets named test_main

# Build rule for target.
test_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_main
.PHONY : test_main

# fast build rule for target.
test_main/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_main.dir/build.make tests/CMakeFiles/test_main.dir/build
.PHONY : test_main/fast

#=============================================================================
# Target rules for targets named test_material

# Build rule for target.
test_material: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_material
.PHONY : test_material

# fast build rule for target.
test_material/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_material.dir/build.make tests/CMakeFiles/test_material.dir/build
.PHONY : test_material/fast

#=============================================================================
# Target rules for targets named test_metric_stack

# Build rule for target.
test_metric_stack: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_metric_stack
.PHONY : test_metric_stack

# fast build rule for target.
test_metric_stack/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_metric_stack.dir/build.make tests/CMakeFiles/test_metric_stack.dir/build
.PHONY : test_metric_stack/fast

#=============================================================================
# Target rules for targets named test_path_traversal

# Build rule for target.
test_path_traversal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_path_traversal
.PHONY : test_path_traversal

# fast build rule for target.
test_path_traversal/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_path_traversal.dir/build.make tests/CMakeFiles/test_path_traversal.dir/build
.PHONY : test_path_traversal/fast

#=============================================================================
# Target rules for targets named test_pbr

# Build rule for target.
test_pbr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_pbr
.PHONY : test_pbr

# fast build rule for target.
test_pbr/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_pbr.dir/build.make tests/CMakeFiles/test_pbr.dir/build
.PHONY : test_pbr/fast

#=============================================================================
# Target rules for targets named test_perf_timer

# Build rule for target.
test_perf_timer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_perf_timer
.PHONY : test_perf_timer

# fast build rule for target.
test_perf_timer/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_perf_timer.dir/build.make tests/CMakeFiles/test_perf_timer.dir/build
.PHONY : test_perf_timer/fast

#=============================================================================
# Target rules for targets named test_postprocess

# Build rule for target.
test_postprocess: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_postprocess
.PHONY : test_postprocess

# fast build rule for target.
test_postprocess/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_postprocess.dir/build.make tests/CMakeFiles/test_postprocess.dir/build
.PHONY : test_postprocess/fast

#=============================================================================
# Target rules for targets named test_render_utils

# Build rule for target.
test_render_utils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_render_utils
.PHONY : test_render_utils

# fast build rule for target.
test_render_utils/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_render_utils.dir/build.make tests/CMakeFiles/test_render_utils.dir/build
.PHONY : test_render_utils/fast

#=============================================================================
# Target rules for targets named test_shader

# Build rule for target.
test_shader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_shader
.PHONY : test_shader

# fast build rule for target.
test_shader/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_shader.dir/build.make tests/CMakeFiles/test_shader.dir/build
.PHONY : test_shader/fast

#=============================================================================
# Target rules for targets named test_shader_api

# Build rule for target.
test_shader_api: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_shader_api
.PHONY : test_shader_api

# fast build rule for target.
test_shader_api/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_shader_api.dir/build.make tests/CMakeFiles/test_shader_api.dir/build
.PHONY : test_shader_api/fast

#=============================================================================
# Target rules for targets named test_shader_include_manual

# Build rule for target.
test_shader_include_manual: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_shader_include_manual
.PHONY : test_shader_include_manual

# fast build rule for target.
test_shader_include_manual/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_shader_include_manual.dir/build.make tests/CMakeFiles/test_shader_include_manual.dir/build
.PHONY : test_shader_include_manual/fast

#=============================================================================
# Target rules for targets named test_shader_security

# Build rule for target.
test_shader_security: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_shader_security
.PHONY : test_shader_security

# fast build rule for target.
test_shader_security/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_shader_security.dir/build.make tests/CMakeFiles/test_shader_security.dir/build
.PHONY : test_shader_security/fast

#=============================================================================
# Target rules for targets named test_skybox

# Build rule for target.
test_skybox: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_skybox
.PHONY : test_skybox

# fast build rule for target.
test_skybox/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_skybox.dir/build.make tests/CMakeFiles/test_skybox.dir/build
.PHONY : test_skybox/fast

#=============================================================================
# Target rules for targets named test_sphere_sorting

# Build rule for target.
test_sphere_sorting: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_sphere_sorting
.PHONY : test_sphere_sorting

# fast build rule for target.
test_sphere_sorting/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_sphere_sorting.dir/build.make tests/CMakeFiles/test_sphere_sorting.dir/build
.PHONY : test_sphere_sorting/fast

#=============================================================================
# Target rules for targets named test_ssbo_rendering

# Build rule for target.
test_ssbo_rendering: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ssbo_rendering
.PHONY : test_ssbo_rendering

# fast build rule for target.
test_ssbo_rendering/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_ssbo_rendering.dir/build.make tests/CMakeFiles/test_ssbo_rendering.dir/build
.PHONY : test_ssbo_rendering/fast

#=============================================================================
# Target rules for targets named test_stb_image_impl

# Build rule for target.
test_stb_image_impl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_stb_image_impl
.PHONY : test_stb_image_impl

# fast build rule for target.
test_stb_image_impl/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_stb_image_impl.dir/build.make tests/CMakeFiles/test_stb_image_impl.dir/build
.PHONY : test_stb_image_impl/fast

#=============================================================================
# Target rules for targets named test_texture

# Build rule for target.
test_texture: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_texture
.PHONY : test_texture

# fast build rule for target.
test_texture/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_texture.dir/build.make tests/CMakeFiles/test_texture.dir/build
.PHONY : test_texture/fast

#=============================================================================
# Target rules for targets named test_texture_security

# Build rule for target.
test_texture_security: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_texture_security
.PHONY : test_texture_security

# fast build rule for target.
test_texture_security/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_texture_security.dir/build.make tests/CMakeFiles/test_texture_security.dir/build
.PHONY : test_texture_security/fast

#=============================================================================
# Target rules for targets named test_ui

# Build rule for target.
test_ui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_ui
.PHONY : test_ui

# fast build rule for target.
test_ui/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/test_ui.dir/build.make tests/CMakeFiles/test_ui.dir/build
.PHONY : test_ui/fast

src/action_notifier.o: src/action_notifier.c.o
.PHONY : src/action_notifier.o

# target to build an object file
src/action_notifier.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/action_notifier.c.o
.PHONY : src/action_notifier.c.o

src/action_notifier.i: src/action_notifier.c.i
.PHONY : src/action_notifier.i

# target to preprocess a source file
src/action_notifier.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/action_notifier.c.i
.PHONY : src/action_notifier.c.i

src/action_notifier.s: src/action_notifier.c.s
.PHONY : src/action_notifier.s

# target to generate assembly for a file
src/action_notifier.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/action_notifier.c.s
.PHONY : src/action_notifier.c.s

src/adaptive_sampler.o: src/adaptive_sampler.c.o
.PHONY : src/adaptive_sampler.o

# target to build an object file
src/adaptive_sampler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/adaptive_sampler.c.o
.PHONY : src/adaptive_sampler.c.o

src/adaptive_sampler.i: src/adaptive_sampler.c.i
.PHONY : src/adaptive_sampler.i

# target to preprocess a source file
src/adaptive_sampler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/adaptive_sampler.c.i
.PHONY : src/adaptive_sampler.c.i

src/adaptive_sampler.s: src/adaptive_sampler.c.s
.PHONY : src/adaptive_sampler.s

# target to generate assembly for a file
src/adaptive_sampler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/adaptive_sampler.c.s
.PHONY : src/adaptive_sampler.c.s

src/app.o: src/app.c.o
.PHONY : src/app.o

# target to build an object file
src/app.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/app.c.o
.PHONY : src/app.c.o

src/app.i: src/app.c.i
.PHONY : src/app.i

# target to preprocess a source file
src/app.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/app.c.i
.PHONY : src/app.c.i

src/app.s: src/app.c.s
.PHONY : src/app.s

# target to generate assembly for a file
src/app.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/app.c.s
.PHONY : src/app.c.s

src/app_env.o: src/app_env.c.o
.PHONY : src/app_env.o

# target to build an object file
src/app_env.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/app_env.c.o
.PHONY : src/app_env.c.o

src/app_env.i: src/app_env.c.i
.PHONY : src/app_env.i

# target to preprocess a source file
src/app_env.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/app_env.c.i
.PHONY : src/app_env.c.i

src/app_env.s: src/app_env.c.s
.PHONY : src/app_env.s

# target to generate assembly for a file
src/app_env.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/app_env.c.s
.PHONY : src/app_env.c.s

src/app_input.o: src/app_input.c.o
.PHONY : src/app_input.o

# target to build an object file
src/app_input.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/app_input.c.o
.PHONY : src/app_input.c.o

src/app_input.i: src/app_input.c.i
.PHONY : src/app_input.i

# target to preprocess a source file
src/app_input.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/app_input.c.i
.PHONY : src/app_input.c.i

src/app_input.s: src/app_input.c.s
.PHONY : src/app_input.s

# target to generate assembly for a file
src/app_input.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/app_input.c.s
.PHONY : src/app_input.c.s

src/app_metrics.o: src/app_metrics.c.o
.PHONY : src/app_metrics.o

# target to build an object file
src/app_metrics.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/app_metrics.c.o
.PHONY : src/app_metrics.c.o

src/app_metrics.i: src/app_metrics.c.i
.PHONY : src/app_metrics.i

# target to preprocess a source file
src/app_metrics.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/app_metrics.c.i
.PHONY : src/app_metrics.c.i

src/app_metrics.s: src/app_metrics.c.s
.PHONY : src/app_metrics.s

# target to generate assembly for a file
src/app_metrics.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/app_metrics.c.s
.PHONY : src/app_metrics.c.s

src/app_scene.o: src/app_scene.c.o
.PHONY : src/app_scene.o

# target to build an object file
src/app_scene.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/app_scene.c.o
.PHONY : src/app_scene.c.o

src/app_scene.i: src/app_scene.c.i
.PHONY : src/app_scene.i

# target to preprocess a source file
src/app_scene.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/app_scene.c.i
.PHONY : src/app_scene.c.i

src/app_scene.s: src/app_scene.c.s
.PHONY : src/app_scene.s

# target to generate assembly for a file
src/app_scene.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/app_scene.c.s
.PHONY : src/app_scene.c.s

src/app_ui.o: src/app_ui.c.o
.PHONY : src/app_ui.o

# target to build an object file
src/app_ui.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/app_ui.c.o
.PHONY : src/app_ui.c.o

src/app_ui.i: src/app_ui.c.i
.PHONY : src/app_ui.i

# target to preprocess a source file
src/app_ui.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/app_ui.c.i
.PHONY : src/app_ui.c.i

src/app_ui.s: src/app_ui.c.s
.PHONY : src/app_ui.s

# target to generate assembly for a file
src/app_ui.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/app_ui.c.s
.PHONY : src/app_ui.c.s

src/async_loader.o: src/async_loader.c.o
.PHONY : src/async_loader.o

# target to build an object file
src/async_loader.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/async_loader.c.o
.PHONY : src/async_loader.c.o

src/async_loader.i: src/async_loader.c.i
.PHONY : src/async_loader.i

# target to preprocess a source file
src/async_loader.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/async_loader.c.i
.PHONY : src/async_loader.c.i

src/async_loader.s: src/async_loader.c.s
.PHONY : src/async_loader.s

# target to generate assembly for a file
src/async_loader.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/async_loader.c.s
.PHONY : src/async_loader.c.s

src/billboard_rendering.o: src/billboard_rendering.c.o
.PHONY : src/billboard_rendering.o

# target to build an object file
src/billboard_rendering.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/billboard_rendering.c.o
.PHONY : src/billboard_rendering.c.o

src/billboard_rendering.i: src/billboard_rendering.c.i
.PHONY : src/billboard_rendering.i

# target to preprocess a source file
src/billboard_rendering.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/billboard_rendering.c.i
.PHONY : src/billboard_rendering.c.i

src/billboard_rendering.s: src/billboard_rendering.c.s
.PHONY : src/billboard_rendering.s

# target to generate assembly for a file
src/billboard_rendering.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/billboard_rendering.c.s
.PHONY : src/billboard_rendering.c.s

src/camera.o: src/camera.c.o
.PHONY : src/camera.o

# target to build an object file
src/camera.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/camera.c.o
.PHONY : src/camera.c.o

src/camera.i: src/camera.c.i
.PHONY : src/camera.i

# target to preprocess a source file
src/camera.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/camera.c.i
.PHONY : src/camera.c.i

src/camera.s: src/camera.c.s
.PHONY : src/camera.s

# target to generate assembly for a file
src/camera.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/camera.c.s
.PHONY : src/camera.c.s

src/cli.o: src/cli.c.o
.PHONY : src/cli.o

# target to build an object file
src/cli.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/cli.c.o
.PHONY : src/cli.c.o

src/cli.i: src/cli.c.i
.PHONY : src/cli.i

# target to preprocess a source file
src/cli.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/cli.c.i
.PHONY : src/cli.c.i

src/cli.s: src/cli.c.s
.PHONY : src/cli.s

# target to generate assembly for a file
src/cli.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/cli.c.s
.PHONY : src/cli.c.s

src/effect_benchmark.o: src/effect_benchmark.c.o
.PHONY : src/effect_benchmark.o

# target to build an object file
src/effect_benchmark.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/effect_benchmark.c.o
.PHONY : src/effect_benchmark.c.o

src/effect_benchmark.i: src/effect_benchmark.c.i
.PHONY : src/effect_benchmark.i

# target to preprocess a source file
src/effect_benchmark.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/effect_benchmark.c.i
.PHONY : src/effect_benchmark.c.i

src/effect_benchmark.s: src/effect_benchmark.c.s
.PHONY : src/effect_benchmark.s

# target to generate assembly for a file
src/effect_benchmark.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/effect_benchmark.c.s
.PHONY : src/effect_benchmark.c.s

src/effects/fx_auto_exposure.o: src/effects/fx_auto_exposure.c.o
.PHONY : src/effects/fx_auto_exposure.o

# target to build an object file
src/effects/fx_auto_exposure.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/effects/fx_auto_exposure.c.o
.PHONY : src/effects/fx_auto_exposure.c.o

src/effects/fx_auto_exposure.i: src/effects/fx_auto_exposure.c.i
.PHONY : src/effects/fx_auto_exposure.i

# target to preprocess a source file
src/effects/fx_auto_exposure.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/effects/fx_auto_exposure.c.i
.PHONY : src/effects/fx_auto_exposure.c.i

src/effects/fx_auto_exposure.s: src/effects/fx_auto_exposure.c.s
.PHONY : src/effects/fx_auto_exposure.s

# target to generate assembly for a file
src/effects/fx_auto_exposure.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/effects/fx_auto_exposure.c.s
.PHONY : src/effects/fx_auto_exposure.c.s

src/effects/fx_bloom.o: src/effects/fx_bloom.c.o
.PHONY : src/effects/fx_bloom.o

# target to build an object file
src/effects/fx_bloom.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/effects/fx_bloom.c.o
.PHONY : src/effects/fx_bloom.c.o

src/effects/fx_bloom.i: src/effects/fx_bloom.c.i
.PHONY : src/effects/fx_bloom.i

# target to preprocess a source file
src/effects/fx_bloom.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/effects/fx_bloom.c.i
.PHONY : src/effects/fx_bloom.c.i

src/effects/fx_bloom.s: src/effects/fx_bloom.c.s
.PHONY : src/effects/fx_bloom.s

# target to generate assembly for a file
src/effects/fx_bloom.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/effects/fx_bloom.c.s
.PHONY : src/effects/fx_bloom.c.s

src/effects/fx_dof.o: src/effects/fx_dof.c.o
.PHONY : src/effects/fx_dof.o

# target to build an object file
src/effects/fx_dof.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/effects/fx_dof.c.o
.PHONY : src/effects/fx_dof.c.o

src/effects/fx_dof.i: src/effects/fx_dof.c.i
.PHONY : src/effects/fx_dof.i

# target to preprocess a source file
src/effects/fx_dof.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/effects/fx_dof.c.i
.PHONY : src/effects/fx_dof.c.i

src/effects/fx_dof.s: src/effects/fx_dof.c.s
.PHONY : src/effects/fx_dof.s

# target to generate assembly for a file
src/effects/fx_dof.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/effects/fx_dof.c.s
.PHONY : src/effects/fx_dof.c.s

src/effects/fx_motion_blur.o: src/effects/fx_motion_blur.c.o
.PHONY : src/effects/fx_motion_blur.o

# target to build an object file
src/effects/fx_motion_blur.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/effects/fx_motion_blur.c.o
.PHONY : src/effects/fx_motion_blur.c.o

src/effects/fx_motion_blur.i: src/effects/fx_motion_blur.c.i
.PHONY : src/effects/fx_motion_blur.i

# target to preprocess a source file
src/effects/fx_motion_blur.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/effects/fx_motion_blur.c.i
.PHONY : src/effects/fx_motion_blur.c.i

src/effects/fx_motion_blur.s: src/effects/fx_motion_blur.c.s
.PHONY : src/effects/fx_motion_blur.s

# target to generate assembly for a file
src/effects/fx_motion_blur.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/effects/fx_motion_blur.c.s
.PHONY : src/effects/fx_motion_blur.c.s

src/fps.o: src/fps.c.o
.PHONY : src/fps.o

# target to build an object file
src/fps.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/fps.c.o
.PHONY : src/fps.c.o

src/fps.i: src/fps.c.i
.PHONY : src/fps.i

# target to preprocess a source file
src/fps.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/fps.c.i
.PHONY : src/fps.c.i

src/fps.s: src/fps.c.s
.PHONY : src/fps.s

# target to generate assembly for a file
src/fps.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/fps.c.s
.PHONY : src/fps.c.s

src/gl_debug.o: src/gl_debug.c.o
.PHONY : src/gl_debug.o

# target to build an object file
src/gl_debug.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/gl_debug.c.o
.PHONY : src/gl_debug.c.o

src/gl_debug.i: src/gl_debug.c.i
.PHONY : src/gl_debug.i

# target to preprocess a source file
src/gl_debug.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/gl_debug.c.i
.PHONY : src/gl_debug.c.i

src/gl_debug.s: src/gl_debug.c.s
.PHONY : src/gl_debug.s

# target to generate assembly for a file
src/gl_debug.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/gl_debug.c.s
.PHONY : src/gl_debug.c.s

src/gpu_profiler.o: src/gpu_profiler.c.o
.PHONY : src/gpu_profiler.o

# target to build an object file
src/gpu_profiler.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/gpu_profiler.c.o
.PHONY : src/gpu_profiler.c.o

src/gpu_profiler.i: src/gpu_profiler.c.i
.PHONY : src/gpu_profiler.i

# target to preprocess a source file
src/gpu_profiler.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/gpu_profiler.c.i
.PHONY : src/gpu_profiler.c.i

src/gpu_profiler.s: src/gpu_profiler.c.s
.PHONY : src/gpu_profiler.s

# target to generate assembly for a file
src/gpu_profiler.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/gpu_profiler.c.s
.PHONY : src/gpu_profiler.c.s

src/gpu_profiler_ui.o: src/gpu_profiler_ui.c.o
.PHONY : src/gpu_profiler_ui.o

# target to build an object file
src/gpu_profiler_ui.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/gpu_profiler_ui.c.o
.PHONY : src/gpu_profiler_ui.c.o

src/gpu_profiler_ui.i: src/gpu_profiler_ui.c.i
.PHONY : src/gpu_profiler_ui.i

# target to preprocess a source file
src/gpu_profiler_ui.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/gpu_profiler_ui.c.i
.PHONY : src/gpu_profiler_ui.c.i

src/gpu_profiler_ui.s: src/gpu_profiler_ui.c.s
.PHONY : src/gpu_profiler_ui.s

# target to generate assembly for a file
src/gpu_profiler_ui.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/gpu_profiler_ui.c.s
.PHONY : src/gpu_profiler_ui.c.s

src/icosphere.o: src/icosphere.c.o
.PHONY : src/icosphere.o

# target to build an object file
src/icosphere.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/icosphere.c.o
.PHONY : src/icosphere.c.o

src/icosphere.i: src/icosphere.c.i
.PHONY : src/icosphere.i

# target to preprocess a source file
src/icosphere.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/icosphere.c.i
.PHONY : src/icosphere.c.i

src/icosphere.s: src/icosphere.c.s
.PHONY : src/icosphere.s

# target to generate assembly for a file
src/icosphere.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/icosphere.c.s
.PHONY : src/icosphere.c.s

src/instanced_rendering.o: src/instanced_rendering.c.o
.PHONY : src/instanced_rendering.o

# target to build an object file
src/instanced_rendering.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/instanced_rendering.c.o
.PHONY : src/instanced_rendering.c.o

src/instanced_rendering.i: src/instanced_rendering.c.i
.PHONY : src/instanced_rendering.i

# target to preprocess a source file
src/instanced_rendering.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/instanced_rendering.c.i
.PHONY : src/instanced_rendering.c.i

src/instanced_rendering.s: src/instanced_rendering.c.s
.PHONY : src/instanced_rendering.s

# target to generate assembly for a file
src/instanced_rendering.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/instanced_rendering.c.s
.PHONY : src/instanced_rendering.c.s

src/log.o: src/log.c.o
.PHONY : src/log.o

# target to build an object file
src/log.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/log.c.o
.PHONY : src/log.c.o

src/log.i: src/log.c.i
.PHONY : src/log.i

# target to preprocess a source file
src/log.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/log.c.i
.PHONY : src/log.c.i

src/log.s: src/log.c.s
.PHONY : src/log.s

# target to generate assembly for a file
src/log.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/log.c.s
.PHONY : src/log.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/main.c.s
.PHONY : src/main.c.s

src/material.o: src/material.c.o
.PHONY : src/material.o

# target to build an object file
src/material.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/material.c.o
.PHONY : src/material.c.o

src/material.i: src/material.c.i
.PHONY : src/material.i

# target to preprocess a source file
src/material.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/material.c.i
.PHONY : src/material.c.i

src/material.s: src/material.c.s
.PHONY : src/material.s

# target to generate assembly for a file
src/material.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/material.c.s
.PHONY : src/material.c.s

src/metric_stack.o: src/metric_stack.c.o
.PHONY : src/metric_stack.o

# target to build an object file
src/metric_stack.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/metric_stack.c.o
.PHONY : src/metric_stack.c.o

src/metric_stack.i: src/metric_stack.c.i
.PHONY : src/metric_stack.i

# target to preprocess a source file
src/metric_stack.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/metric_stack.c.i
.PHONY : src/metric_stack.c.i

src/metric_stack.s: src/metric_stack.c.s
.PHONY : src/metric_stack.s

# target to generate assembly for a file
src/metric_stack.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/metric_stack.c.s
.PHONY : src/metric_stack.c.s

src/pbr.o: src/pbr.c.o
.PHONY : src/pbr.o

# target to build an object file
src/pbr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/pbr.c.o
.PHONY : src/pbr.c.o

src/pbr.i: src/pbr.c.i
.PHONY : src/pbr.i

# target to preprocess a source file
src/pbr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/pbr.c.i
.PHONY : src/pbr.c.i

src/pbr.s: src/pbr.c.s
.PHONY : src/pbr.s

# target to generate assembly for a file
src/pbr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/pbr.c.s
.PHONY : src/pbr.c.s

src/perf_mode.o: src/perf_mode.c.o
.PHONY : src/perf_mode.o

# target to build an object file
src/perf_mode.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/perf_mode.c.o
.PHONY : src/perf_mode.c.o

src/perf_mode.i: src/perf_mode.c.i
.PHONY : src/perf_mode.i

# target to preprocess a source file
src/perf_mode.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/perf_mode.c.i
.PHONY : src/perf_mode.c.i

src/perf_mode.s: src/perf_mode.c.s
.PHONY : src/perf_mode.s

# target to generate assembly for a file
src/perf_mode.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/perf_mode.c.s
.PHONY : src/perf_mode.c.s

src/perf_timer.o: src/perf_timer.c.o
.PHONY : src/perf_timer.o

# target to build an object file
src/perf_timer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/perf_timer.c.o
.PHONY : src/perf_timer.c.o

src/perf_timer.i: src/perf_timer.c.i
.PHONY : src/perf_timer.i

# target to preprocess a source file
src/perf_timer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/perf_timer.c.i
.PHONY : src/perf_timer.c.i

src/perf_timer.s: src/perf_timer.c.s
.PHONY : src/perf_timer.s

# target to generate assembly for a file
src/perf_timer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/perf_timer.c.s
.PHONY : src/perf_timer.c.s

src/postprocess.o: src/postprocess.c.o
.PHONY : src/postprocess.o

# target to build an object file
src/postprocess.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/postprocess.c.o
.PHONY : src/postprocess.c.o

src/postprocess.i: src/postprocess.c.i
.PHONY : src/postprocess.i

# target to preprocess a source file
src/postprocess.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/postprocess.c.i
.PHONY : src/postprocess.c.i

src/postprocess.s: src/postprocess.c.s
.PHONY : src/postprocess.s

# target to generate assembly for a file
src/postprocess.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/postprocess.c.s
.PHONY : src/postprocess.c.s

src/render_utils.o: src/render_utils.c.o
.PHONY : src/render_utils.o

# target to build an object file
src/render_utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/render_utils.c.o
.PHONY : src/render_utils.c.o

src/render_utils.i: src/render_utils.c.i
.PHONY : src/render_utils.i

# target to preprocess a source file
src/render_utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/render_utils.c.i
.PHONY : src/render_utils.c.i

src/render_utils.s: src/render_utils.c.s
.PHONY : src/render_utils.s

# target to generate assembly for a file
src/render_utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/render_utils.c.s
.PHONY : src/render_utils.c.s

src/shader.o: src/shader.c.o
.PHONY : src/shader.o

# target to build an object file
src/shader.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/shader.c.o
.PHONY : src/shader.c.o

src/shader.i: src/shader.c.i
.PHONY : src/shader.i

# target to preprocess a source file
src/shader.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/shader.c.i
.PHONY : src/shader.c.i

src/shader.s: src/shader.c.s
.PHONY : src/shader.s

# target to generate assembly for a file
src/shader.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/shader.c.s
.PHONY : src/shader.c.s

src/skybox.o: src/skybox.c.o
.PHONY : src/skybox.o

# target to build an object file
src/skybox.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/skybox.c.o
.PHONY : src/skybox.c.o

src/skybox.i: src/skybox.c.i
.PHONY : src/skybox.i

# target to preprocess a source file
src/skybox.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/skybox.c.i
.PHONY : src/skybox.c.i

src/skybox.s: src/skybox.c.s
.PHONY : src/skybox.s

# target to generate assembly for a file
src/skybox.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/skybox.c.s
.PHONY : src/skybox.c.s

src/sphere_sorting.o: src/sphere_sorting.c.o
.PHONY : src/sphere_sorting.o

# target to build an object file
src/sphere_sorting.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/sphere_sorting.c.o
.PHONY : src/sphere_sorting.c.o

src/sphere_sorting.i: src/sphere_sorting.c.i
.PHONY : src/sphere_sorting.i

# target to preprocess a source file
src/sphere_sorting.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/sphere_sorting.c.i
.PHONY : src/sphere_sorting.c.i

src/sphere_sorting.s: src/sphere_sorting.c.s
.PHONY : src/sphere_sorting.s

# target to generate assembly for a file
src/sphere_sorting.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/sphere_sorting.c.s
.PHONY : src/sphere_sorting.c.s

src/ssbo_rendering.o: src/ssbo_rendering.c.o
.PHONY : src/ssbo_rendering.o

# target to build an object file
src/ssbo_rendering.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/ssbo_rendering.c.o
.PHONY : src/ssbo_rendering.c.o

src/ssbo_rendering.i: src/ssbo_rendering.c.i
.PHONY : src/ssbo_rendering.i

# target to preprocess a source file
src/ssbo_rendering.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/ssbo_rendering.c.i
.PHONY : src/ssbo_rendering.c.i

src/ssbo_rendering.s: src/ssbo_rendering.c.s
.PHONY : src/ssbo_rendering.s

# target to generate assembly for a file
src/ssbo_rendering.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/ssbo_rendering.c.s
.PHONY : src/ssbo_rendering.c.s

src/stb_image_impl.o: src/stb_image_impl.c.o
.PHONY : src/stb_image_impl.o

# target to build an object file
src/stb_image_impl.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/stb_image_impl.c.o
.PHONY : src/stb_image_impl.c.o

src/stb_image_impl.i: src/stb_image_impl.c.i
.PHONY : src/stb_image_impl.i

# target to preprocess a source file
src/stb_image_impl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/stb_image_impl.c.i
.PHONY : src/stb_image_impl.c.i

src/stb_image_impl.s: src/stb_image_impl.c.s
.PHONY : src/stb_image_impl.s

# target to generate assembly for a file
src/stb_image_impl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/stb_image_impl.c.s
.PHONY : src/stb_image_impl.c.s

src/texture.o: src/texture.c.o
.PHONY : src/texture.o

# target to build an object file
src/texture.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/texture.c.o
.PHONY : src/texture.c.o

src/texture.i: src/texture.c.i
.PHONY : src/texture.i

# target to preprocess a source file
src/texture.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/texture.c.i
.PHONY : src/texture.c.i

src/texture.s: src/texture.c.s
.PHONY : src/texture.s

# target to generate assembly for a file
src/texture.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/texture.c.s
.PHONY : src/texture.c.s

src/ui.o: src/ui.c.o
.PHONY : src/ui.o

# target to build an object file
src/ui.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/ui.c.o
.PHONY : src/ui.c.o

src/ui.i: src/ui.c.i
.PHONY : src/ui.i

# target to preprocess a source file
src/ui.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/ui.c.i
.PHONY : src/ui.c.i

src/ui.s: src/ui.c.s
.PHONY : src/ui.s

# target to generate assembly for a file
src/ui.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/ui.c.s
.PHONY : src/ui.c.s

src/window.o: src/window.c.o
.PHONY : src/window.o

# target to build an object file
src/window.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/window.c.o
.PHONY : src/window.c.o

src/window.i: src/window.c.i
.PHONY : src/window.i

# target to preprocess a source file
src/window.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/window.c.i
.PHONY : src/window.c.i

src/window.s: src/window.c.s
.PHONY : src/window.s

# target to generate assembly for a file
src/window.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/app.dir/build.make CMakeFiles/app.dir/src/window.c.s
.PHONY : src/window.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... glad-generate-files"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... app"
	@echo "... app_testlib"
	@echo "... cglm"
	@echo "... cjson"
	@echo "... glad"
	@echo "... glfw"
	@echo "... test_adaptive_sampler_frames"
	@echo "... test_app"
	@echo "... test_app_input"
	@echo "... test_app_metrics"
	@echo "... test_async_loader_perf"
	@echo "... test_benchmark_adaptive_sampler"
	@echo "... test_benchmark_bloom"
	@echo "... test_benchmark_histogram"
	@echo "... test_camera"
	@echo "... test_cli"
	@echo "... test_fps"
	@echo "... test_fxaa_synthetic"
	@echo "... test_gpu_profiler"
	@echo "... test_icosphere"
	@echo "... test_instanced_rendering"
	@echo "... test_log"
	@echo "... test_main"
	@echo "... test_material"
	@echo "... test_metric_stack"
	@echo "... test_path_traversal"
	@echo "... test_pbr"
	@echo "... test_perf_timer"
	@echo "... test_postprocess"
	@echo "... test_render_utils"
	@echo "... test_shader"
	@echo "... test_shader_api"
	@echo "... test_shader_include_manual"
	@echo "... test_shader_security"
	@echo "... test_skybox"
	@echo "... test_sphere_sorting"
	@echo "... test_ssbo_rendering"
	@echo "... test_stb_image_impl"
	@echo "... test_texture"
	@echo "... test_texture_security"
	@echo "... test_ui"
	@echo "... unity"
	@echo "... src/action_notifier.o"
	@echo "... src/action_notifier.i"
	@echo "... src/action_notifier.s"
	@echo "... src/adaptive_sampler.o"
	@echo "... src/adaptive_sampler.i"
	@echo "... src/adaptive_sampler.s"
	@echo "... src/app.o"
	@echo "... src/app.i"
	@echo "... src/app.s"
	@echo "... src/app_env.o"
	@echo "... src/app_env.i"
	@echo "... src/app_env.s"
	@echo "... src/app_input.o"
	@echo "... src/app_input.i"
	@echo "... src/app_input.s"
	@echo "... src/app_metrics.o"
	@echo "... src/app_metrics.i"
	@echo "... src/app_metrics.s"
	@echo "... src/app_scene.o"
	@echo "... src/app_scene.i"
	@echo "... src/app_scene.s"
	@echo "... src/app_ui.o"
	@echo "... src/app_ui.i"
	@echo "... src/app_ui.s"
	@echo "... src/async_loader.o"
	@echo "... src/async_loader.i"
	@echo "... src/async_loader.s"
	@echo "... src/billboard_rendering.o"
	@echo "... src/billboard_rendering.i"
	@echo "... src/billboard_rendering.s"
	@echo "... src/camera.o"
	@echo "... src/camera.i"
	@echo "... src/camera.s"
	@echo "... src/cli.o"
	@echo "... src/cli.i"
	@echo "... src/cli.s"
	@echo "... src/effect_benchmark.o"
	@echo "... src/effect_benchmark.i"
	@echo "... src/effect_benchmark.s"
	@echo "... src/effects/fx_auto_exposure.o"
	@echo "... src/effects/fx_auto_exposure.i"
	@echo "... src/effects/fx_auto_exposure.s"
	@echo "... src/effects/fx_bloom.o"
	@echo "... src/effects/fx_bloom.i"
	@echo "... src/effects/fx_bloom.s"
	@echo "... src/effects/fx_dof.o"
	@echo "... src/effects/fx_dof.i"
	@echo "... src/effects/fx_dof.s"
	@echo "... src/effects/fx_motion_blur.o"
	@echo "... src/effects/fx_motion_blur.i"
	@echo "... src/effects/fx_motion_blur.s"
	@echo "... src/fps.o"
	@echo "... src/fps.i"
	@echo "... src/fps.s"
	@echo "... src/gl_debug.o"
	@echo "... src/gl_debug.i"
	@echo "... src/gl_debug.s"
	@echo "... src/gpu_profiler.o"
	@echo "... src/gpu_profiler.i"
	@echo "... src/gpu_profiler.s"
	@echo "... src/gpu_profiler_ui.o"
	@echo "... src/gpu_profiler_ui.i"
	@echo "... src/gpu_profiler_ui.s"
	@echo "... src/icosphere.o"
	@echo "... src/icosphere.i"
	@echo "... src/icosphere.s"
	@echo "... src/instanced_rendering.o"
	@echo "... src/instanced_rendering.i"
	@echo "... src/instanced_rendering.s"
	@echo "... src/log.o"
	@echo "... src/log.i"
	@echo "... src/log.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/material.o"
	@echo "... src/material.i"
	@echo "... src/material.s"
	@echo "... src/metric_stack.o"
	@echo "... src/metric_stack.i"
	@echo "... src/metric_stack.s"
	@echo "... src/pbr.o"
	@echo "... src/pbr.i"
	@echo "... src/pbr.s"
	@echo "... src/perf_mode.o"
	@echo "... src/perf_mode.i"
	@echo "... src/perf_mode.s"
	@echo "... src/perf_timer.o"
	@echo "... src/perf_timer.i"
	@echo "... src/perf_timer.s"
	@echo "... src/postprocess.o"
	@echo "... src/postprocess.i"
	@echo "... src/postprocess.s"
	@echo "... src/render_utils.o"
	@echo "... src/render_utils.i"
	@echo "... src/render_utils.s"
	@echo "... src/shader.o"
	@echo "... src/shader.i"
	@echo "... src/shader.s"
	@echo "... src/skybox.o"
	@echo "... src/skybox.i"
	@echo "... src/skybox.s"
	@echo "... src/sphere_sorting.o"
	@echo "... src/sphere_sorting.i"
	@echo "... src/sphere_sorting.s"
	@echo "... src/ssbo_rendering.o"
	@echo "... src/ssbo_rendering.i"
	@echo "... src/ssbo_rendering.s"
	@echo "... src/stb_image_impl.o"
	@echo "... src/stb_image_impl.i"
	@echo "... src/stb_image_impl.s"
	@echo "... src/texture.o"
	@echo "... src/texture.i"
	@echo "... src/texture.s"
	@echo "... src/ui.o"
	@echo "... src/ui.i"
	@echo "... src/ui.s"
	@echo "... src/window.o"
	@echo "... src/window.i"
	@echo "... src/window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /app/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system
