[project]
name = "suckless-ogl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyautogui>=0.9.54",
    "pygments<2.21.0",
    "typer[all]>=0.26.7",
    "vdf>=3.4",
]

[dependency-groups]
dev = [
    "basedpyright>=1.39.9",
    "pylint>=4.0.6",
    "ruff>=0.15.18",
]

[tool.basedpyright]
typeCheckingMode = "strict"
pythonVersion = "3.12"
# Ignore les warnings sur les types dépréciés si nécessaire
reportDeprecated = "warning"
