# CMake generated Testfile for
# Source directory: /home/latty/Prog/__PERSO__/suckless-ogl/tests
# Build directory: /home/latty/Prog/__PERSO__/suckless-ogl/tests
#
# This file includes the relevant testing commands required for
# testing this directory and lists subdirectories to be tested as well.
add_test(test_app "/home/latty/Prog/__PERSO__/suckless-ogl/tests/run_test_with_xvfb.sh" "/home/latty/Prog/__PERSO__/suckless-ogl/tests/test_app")
set_tests_properties(test_app PROPERTIES  WORKING_DIRECTORY "/home/latty/Prog/__PERSO__/suckless-ogl" _BACKTRACE_TRIPLES "/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;71;add_test;/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;0;")
add_test(test_camera "/home/latty/Prog/__PERSO__/suckless-ogl/tests/test_camera")
set_tests_properties(test_camera PROPERTIES  WORKING_DIRECTORY "/home/latty/Prog/__PERSO__/suckless-ogl" _BACKTRACE_TRIPLES "/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;76;add_test;/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;0;")
add_test(test_fps "/home/latty/Prog/__PERSO__/suckless-ogl/tests/test_fps")
set_tests_properties(test_fps PROPERTIES  WORKING_DIRECTORY "/home/latty/Prog/__PERSO__/suckless-ogl" _BACKTRACE_TRIPLES "/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;76;add_test;/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;0;")
add_test(test_fxaa_synthetic "/home/latty/Prog/__PERSO__/suckless-ogl/tests/run_test_with_xvfb.sh" "/home/latty/Prog/__PERSO__/suckless-ogl/tests/test_fxaa_synthetic")
set_tests_properties(test_fxaa_synthetic PROPERTIES  WORKING_DIRECTORY "/home/latty/Prog/__PERSO__/suckless-ogl" _BACKTRACE_TRIPLES "/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;71;add_test;/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;0;")
add_test(test_icosphere "/home/latty/Prog/__PERSO__/suckless-ogl/tests/test_icosphere")
set_tests_properties(test_icosphere PROPERTIES  WORKING_DIRECTORY "/home/latty/Prog/__PERSO__/suckless-ogl" _BACKTRACE_TRIPLES "/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;76;add_test;/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;0;")
add_test(test_instanced_rendering "/home/latty/Prog/__PERSO__/suckless-ogl/tests/run_test_with_xvfb.sh" "/home/latty/Prog/__PERSO__/suckless-ogl/tests/test_instanced_rendering")
set_tests_properties(test_instanced_rendering PROPERTIES  WORKING_DIRECTORY "/home/latty/Prog/__PERSO__/suckless-ogl" _BACKTRACE_TRIPLES "/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;71;add_test;/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;0;")
add_test(test_log "/home/latty/Prog/__PERSO__/suckless-ogl/tests/test_log")
set_tests_properties(test_log PROPERTIES  WORKING_DIRECTORY "/home/latty/Prog/__PERSO__/suckless-ogl" _BACKTRACE_TRIPLES "/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;76;add_test;/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;0;")
add_test(test_main "/home/latty/Prog/__PERSO__/suckless-ogl/tests/test_main")
set_tests_properties(test_main PROPERTIES  WORKING_DIRECTORY "/home/latty/Prog/__PERSO__/suckless-ogl" _BACKTRACE_TRIPLES "/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;76;add_test;/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;0;")
add_test(test_material "/home/latty/Prog/__PERSO__/suckless-ogl/tests/run_test_with_xvfb.sh" "/home/latty/Prog/__PERSO__/suckless-ogl/tests/test_material")
set_tests_properties(test_material PROPERTIES  WORKING_DIRECTORY "/home/latty/Prog/__PERSO__/suckless-ogl" _BACKTRACE_TRIPLES "/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;71;add_test;/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;0;")
add_test(test_pbr "/home/latty/Prog/__PERSO__/suckless-ogl/tests/run_test_with_xvfb.sh" "/home/latty/Prog/__PERSO__/suckless-ogl/tests/test_pbr")
set_tests_properties(test_pbr PROPERTIES  WORKING_DIRECTORY "/home/latty/Prog/__PERSO__/suckless-ogl" _BACKTRACE_TRIPLES "/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;71;add_test;/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;0;")
add_test(test_perf_timer "/home/latty/Prog/__PERSO__/suckless-ogl/tests/test_perf_timer")
set_tests_properties(test_perf_timer PROPERTIES  WORKING_DIRECTORY "/home/latty/Prog/__PERSO__/suckless-ogl" _BACKTRACE_TRIPLES "/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;76;add_test;/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;0;")
add_test(test_postprocess "/home/latty/Prog/__PERSO__/suckless-ogl/tests/run_test_with_xvfb.sh" "/home/latty/Prog/__PERSO__/suckless-ogl/tests/test_postprocess")
set_tests_properties(test_postprocess PROPERTIES  WORKING_DIRECTORY "/home/latty/Prog/__PERSO__/suckless-ogl" _BACKTRACE_TRIPLES "/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;71;add_test;/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;0;")
add_test(test_render_utils "/home/latty/Prog/__PERSO__/suckless-ogl/tests/run_test_with_xvfb.sh" "/home/latty/Prog/__PERSO__/suckless-ogl/tests/test_render_utils")
set_tests_properties(test_render_utils PROPERTIES  WORKING_DIRECTORY "/home/latty/Prog/__PERSO__/suckless-ogl" _BACKTRACE_TRIPLES "/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;71;add_test;/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;0;")
add_test(test_shader "/home/latty/Prog/__PERSO__/suckless-ogl/tests/run_test_with_xvfb.sh" "/home/latty/Prog/__PERSO__/suckless-ogl/tests/test_shader")
set_tests_properties(test_shader PROPERTIES  WORKING_DIRECTORY "/home/latty/Prog/__PERSO__/suckless-ogl" _BACKTRACE_TRIPLES "/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;71;add_test;/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;0;")
add_test(test_shader_api "/home/latty/Prog/__PERSO__/suckless-ogl/tests/run_test_with_xvfb.sh" "/home/latty/Prog/__PERSO__/suckless-ogl/tests/test_shader_api")
set_tests_properties(test_shader_api PROPERTIES  WORKING_DIRECTORY "/home/latty/Prog/__PERSO__/suckless-ogl" _BACKTRACE_TRIPLES "/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;71;add_test;/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;0;")
add_test(test_shader_include_manual "/home/latty/Prog/__PERSO__/suckless-ogl/tests/test_shader_include_manual")
set_tests_properties(test_shader_include_manual PROPERTIES  WORKING_DIRECTORY "/home/latty/Prog/__PERSO__/suckless-ogl" _BACKTRACE_TRIPLES "/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;76;add_test;/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;0;")
add_test(test_skybox "/home/latty/Prog/__PERSO__/suckless-ogl/tests/run_test_with_xvfb.sh" "/home/latty/Prog/__PERSO__/suckless-ogl/tests/test_skybox")
set_tests_properties(test_skybox PROPERTIES  WORKING_DIRECTORY "/home/latty/Prog/__PERSO__/suckless-ogl" _BACKTRACE_TRIPLES "/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;71;add_test;/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;0;")
add_test(test_sphere_sorting "/home/latty/Prog/__PERSO__/suckless-ogl/tests/test_sphere_sorting")
set_tests_properties(test_sphere_sorting PROPERTIES  WORKING_DIRECTORY "/home/latty/Prog/__PERSO__/suckless-ogl" _BACKTRACE_TRIPLES "/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;76;add_test;/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;0;")
add_test(test_ssbo_rendering "/home/latty/Prog/__PERSO__/suckless-ogl/tests/run_test_with_xvfb.sh" "/home/latty/Prog/__PERSO__/suckless-ogl/tests/test_ssbo_rendering")
set_tests_properties(test_ssbo_rendering PROPERTIES  WORKING_DIRECTORY "/home/latty/Prog/__PERSO__/suckless-ogl" _BACKTRACE_TRIPLES "/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;71;add_test;/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;0;")
add_test(test_stb_image_impl "/home/latty/Prog/__PERSO__/suckless-ogl/tests/test_stb_image_impl")
set_tests_properties(test_stb_image_impl PROPERTIES  WORKING_DIRECTORY "/home/latty/Prog/__PERSO__/suckless-ogl" _BACKTRACE_TRIPLES "/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;76;add_test;/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;0;")
add_test(test_texture "/home/latty/Prog/__PERSO__/suckless-ogl/tests/run_test_with_xvfb.sh" "/home/latty/Prog/__PERSO__/suckless-ogl/tests/test_texture")
set_tests_properties(test_texture PROPERTIES  WORKING_DIRECTORY "/home/latty/Prog/__PERSO__/suckless-ogl" _BACKTRACE_TRIPLES "/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;71;add_test;/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;0;")
add_test(test_ui "/home/latty/Prog/__PERSO__/suckless-ogl/tests/run_test_with_xvfb.sh" "/home/latty/Prog/__PERSO__/suckless-ogl/tests/test_ui")
set_tests_properties(test_ui PROPERTIES  WORKING_DIRECTORY "/home/latty/Prog/__PERSO__/suckless-ogl" _BACKTRACE_TRIPLES "/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;71;add_test;/home/latty/Prog/__PERSO__/suckless-ogl/tests/CMakeLists.txt;0;")
