# CMake generated Testfile for
# Source directory: /app/tests
# Build directory: /app/tests
#
# This file includes the relevant testing commands required for
# testing this directory and lists subdirectories to be tested as well.
add_test(test_adaptive_sampler_frames "/app/tests/test_adaptive_sampler_frames")
set_tests_properties(test_adaptive_sampler_frames PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;83;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_app "/app/tests/run_test_with_xvfb.sh" "/app/tests/test_app")
set_tests_properties(test_app PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;78;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_app_input "/app/tests/run_test_with_xvfb.sh" "/app/tests/test_app_input")
set_tests_properties(test_app_input PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;78;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_app_metrics "/app/tests/run_test_with_xvfb.sh" "/app/tests/test_app_metrics")
set_tests_properties(test_app_metrics PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;78;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_async_loader_perf "/app/tests/test_async_loader_perf")
set_tests_properties(test_async_loader_perf PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;83;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_benchmark_adaptive_sampler "/app/tests/test_benchmark_adaptive_sampler")
set_tests_properties(test_benchmark_adaptive_sampler PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;83;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_benchmark_bloom "/app/tests/run_test_with_xvfb.sh" "/app/tests/test_benchmark_bloom")
set_tests_properties(test_benchmark_bloom PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;78;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_benchmark_histogram "/app/tests/run_test_with_xvfb.sh" "/app/tests/test_benchmark_histogram")
set_tests_properties(test_benchmark_histogram PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;78;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_camera "/app/tests/test_camera")
set_tests_properties(test_camera PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;83;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_cli "/app/tests/test_cli")
set_tests_properties(test_cli PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;83;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_fps "/app/tests/test_fps")
set_tests_properties(test_fps PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;83;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_fxaa_synthetic "/app/tests/run_test_with_xvfb.sh" "/app/tests/test_fxaa_synthetic")
set_tests_properties(test_fxaa_synthetic PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;78;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_gpu_profiler "/app/tests/run_test_with_xvfb.sh" "/app/tests/test_gpu_profiler")
set_tests_properties(test_gpu_profiler PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;78;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_icosphere "/app/tests/test_icosphere")
set_tests_properties(test_icosphere PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;83;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_instanced_rendering "/app/tests/run_test_with_xvfb.sh" "/app/tests/test_instanced_rendering")
set_tests_properties(test_instanced_rendering PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;78;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_log "/app/tests/test_log")
set_tests_properties(test_log PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;83;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_main "/app/tests/test_main")
set_tests_properties(test_main PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;83;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_material "/app/tests/run_test_with_xvfb.sh" "/app/tests/test_material")
set_tests_properties(test_material PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;78;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_metric_stack "/app/tests/test_metric_stack")
set_tests_properties(test_metric_stack PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;83;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_path_traversal "/app/tests/test_path_traversal")
set_tests_properties(test_path_traversal PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;83;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_pbr "/app/tests/run_test_with_xvfb.sh" "/app/tests/test_pbr")
set_tests_properties(test_pbr PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;78;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_perf_timer "/app/tests/test_perf_timer")
set_tests_properties(test_perf_timer PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;83;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_postprocess "/app/tests/run_test_with_xvfb.sh" "/app/tests/test_postprocess")
set_tests_properties(test_postprocess PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;78;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_render_utils "/app/tests/run_test_with_xvfb.sh" "/app/tests/test_render_utils")
set_tests_properties(test_render_utils PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;78;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_shader "/app/tests/run_test_with_xvfb.sh" "/app/tests/test_shader")
set_tests_properties(test_shader PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;78;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_shader_api "/app/tests/run_test_with_xvfb.sh" "/app/tests/test_shader_api")
set_tests_properties(test_shader_api PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;78;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_shader_include_manual "/app/tests/test_shader_include_manual")
set_tests_properties(test_shader_include_manual PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;83;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_shader_security "/app/tests/test_shader_security")
set_tests_properties(test_shader_security PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;83;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_skybox "/app/tests/run_test_with_xvfb.sh" "/app/tests/test_skybox")
set_tests_properties(test_skybox PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;78;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_sphere_sorting "/app/tests/test_sphere_sorting")
set_tests_properties(test_sphere_sorting PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;83;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_ssbo_rendering "/app/tests/run_test_with_xvfb.sh" "/app/tests/test_ssbo_rendering")
set_tests_properties(test_ssbo_rendering PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;78;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_stb_image_impl "/app/tests/test_stb_image_impl")
set_tests_properties(test_stb_image_impl PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;83;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_texture "/app/tests/run_test_with_xvfb.sh" "/app/tests/test_texture")
set_tests_properties(test_texture PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;78;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_texture_security "/app/tests/run_test_with_xvfb.sh" "/app/tests/test_texture_security")
set_tests_properties(test_texture_security PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;78;add_test;/app/tests/CMakeLists.txt;0;")
add_test(test_ui "/app/tests/run_test_with_xvfb.sh" "/app/tests/test_ui")
set_tests_properties(test_ui PROPERTIES  WORKING_DIRECTORY "/app" _BACKTRACE_TRIPLES "/app/tests/CMakeLists.txt;78;add_test;/app/tests/CMakeLists.txt;0;")
