#ifndef MOCK_GL_STANDALONE_H
#define MOCK_GL_STANDALONE_H

#include "glad/glad.h"

/* Helper functions for controlling mock behavior */

/**
 * @brief Resets all call counters and internal state.
 */
void mock_gl_reset_calls(void);

/**
 * @brief Returns the last ID generated by glGenBuffers.
 */
GLuint mock_gl_get_generated_buffer_id(void);

/**
 * @brief Returns the last ID generated by glGenVertexArrays.
 */
GLuint mock_gl_get_generated_vao_id(void);

/**
 * @brief Returns the last buffer ID deleted by glDeleteBuffers.
 */
GLuint mock_gl_get_last_deleted_buffer(void);

/**
 * @brief Returns the total number of calls to glDeleteBuffers.
 */
int mock_gl_get_delete_buffer_call_count(void);

/**
 * @brief Returns the total number of calls to glBufferData.
 */
int mock_gl_get_buffer_data_call_count(void);

/**
 * @brief Returns the total number of calls to glBufferSubData.
 */
int mock_gl_get_buffer_sub_data_call_count(void);

/**
 * @brief Returns the size of the last glBufferData call.
 */
GLsizeiptr mock_gl_get_last_buffer_data_size(void);

/**
 * @brief Returns the size of the last glBufferSubData call.
 */
GLsizeiptr mock_gl_get_last_buffer_sub_data_size(void);

/* Default IDs returned by mocks */
#define DEFAULT_BUFFER_ID 100
#define DEFAULT_VAO_ID 200

#endif /* MOCK_GL_STANDALONE_H */
