#ifndef POSTPROCESS_PRESETS_H
#define POSTPROCESS_PRESETS_H

#include "postprocess.h"

/*
 * Definitions des presets de post-traitement.
 * Ces constantes sont définies ici pour être accessibles via include
 * sans nécessiter de compilation séparée.
 */

static const PostProcessPreset PRESET_DEFAULT = {
    .active_effects = (unsigned int)POSTFX_EXPOSURE,
    .vignette = {.intensity = DEFAULT_VIGNETTE_INTENSITY,
                 .extent = DEFAULT_VIGNETTE_EXTENT},
    .grain = {.intensity = DEFAULT_GRAIN_INTENSITY,
              .intensity_shadows = 1.0F,
              .intensity_midtones = 1.0F,
              .intensity_highlights = 1.0F,
              .shadows_max = 0.09F,
              .highlights_min = 0.5F,
              .texel_size = 1.0F},
    .exposure = {.exposure = DEFAULT_EXPOSURE},
    .chrom_abbr = {.strength = DEFAULT_CHROM_ABBR_STRENGTH},
    .white_balance = {.temperature = DEFAULT_WB_TEMP, .tint = DEFAULT_WB_TINT},
    .color_grading = {.saturation = 1.0F,
                      .contrast = 1.0F,
                      .gamma = 1.0F,
                      .gain = 1.0F,
                      .offset = 0.0F},
    .tonemapper = {.slope = DEFAULT_FILMIC_SLOPE,
                   .toe = DEFAULT_FILMIC_TOE,
                   .shoulder = DEFAULT_FILMIC_SHOULDER,
                   .black_clip = DEFAULT_FILMIC_BLACK_CLIP,
                   .white_clip = DEFAULT_FILMIC_WHITE_CLIP},
    .bloom = {.intensity = 0.0F,
              .threshold = 1.0F,
              .soft_threshold = 0.5F,
              .radius = 1.0F},
    .dof = {.focal_distance = DEFAULT_DOF_FOCAL_DISTANCE,
            .focal_range = DEFAULT_DOF_FOCAL_RANGE,
            .bokeh_scale = DEFAULT_DOF_BOKEH_SCALE}};

static const PostProcessPreset PRESET_SUBTLE = {
    .active_effects =
        (unsigned int)POSTFX_VIGNETTE | (unsigned int)POSTFX_GRAIN |
        (unsigned int)POSTFX_EXPOSURE | (unsigned int)POSTFX_COLOR_GRADING,
    .vignette = {.intensity = 0.3F, .extent = 0.7F},
    .grain = {.intensity = 0.02F,
              .intensity_shadows = 1.0F,
              .intensity_midtones = 1.0F,
              .intensity_highlights = 1.0F,
              .shadows_max = 0.09F,
              .highlights_min = 0.5F,
              .texel_size = 1.0F},
    .exposure = {.exposure = DEFAULT_EXPOSURE},
    .chrom_abbr = {.strength = 0.01F},
    .white_balance = {.temperature = DEFAULT_WB_TEMP, .tint = DEFAULT_WB_TINT},
    .color_grading = {.saturation = 1.0F,
                      .contrast = 1.0F,
                      .gamma = 1.0F,
                      .gain = 1.0F,
                      .offset = 0.0F},
    .tonemapper = {.slope = DEFAULT_FILMIC_SLOPE,
                   .toe = DEFAULT_FILMIC_TOE,
                   .shoulder = DEFAULT_FILMIC_SHOULDER,
                   .black_clip = DEFAULT_FILMIC_BLACK_CLIP,
                   .white_clip = DEFAULT_FILMIC_WHITE_CLIP},
    .bloom = {.intensity = 0.02F,
              .threshold = 1.0F,
              .soft_threshold = 0.5F,
              .radius = 1.0F},
    .dof = {.focal_distance = DEFAULT_DOF_FOCAL_DISTANCE,
            .focal_range = DEFAULT_DOF_FOCAL_RANGE,
            .bokeh_scale = DEFAULT_DOF_BOKEH_SCALE}};

static const PostProcessPreset PRESET_CINEMATIC = {
    (unsigned int)POSTFX_VIGNETTE | (unsigned int)POSTFX_GRAIN |
        (unsigned int)POSTFX_AUTO_EXPOSURE | (unsigned int)POSTFX_BLOOM |
        (unsigned int)POSTFX_DOF | (unsigned int)POSTFX_COLOR_GRADING |
        (unsigned int)POSTFX_MOTION_BLUR,
    .vignette = {.intensity = 0.5F, .extent = 0.6F},
    .grain = {.intensity = 0.03F,
              .intensity_shadows = 1.2F,
              .intensity_midtones = 1.0F,
              .intensity_highlights = 0.8F,
              .shadows_max = 0.09F,
              .highlights_min = 0.5F,
              .texel_size = 1.0F},
    .exposure = {.exposure = 1.2F},
    .chrom_abbr = {.strength = 0.015F},
    .white_balance = {.temperature = 6500.0F, .tint = -0.05F},
    .color_grading = {.saturation = 1.0F,
                      .contrast = 1.0F,
                      .gamma = 1.0F,
                      .gain = 1.0F,
                      .offset = 0.0F},
    .tonemapper = {.slope = DEFAULT_FILMIC_SLOPE,
                   .toe = DEFAULT_FILMIC_TOE,
                   .shoulder = DEFAULT_FILMIC_SHOULDER,
                   .black_clip = DEFAULT_FILMIC_BLACK_CLIP,
                   .white_clip = DEFAULT_FILMIC_WHITE_CLIP},
    .bloom = {.intensity = 0.04F,
              .threshold = 1.0F,
              .soft_threshold = 0.5F,
              .radius = 1.0F},
    .dof = {.focal_distance = DEFAULT_DOF_FOCAL_DISTANCE,
            .focal_range = DEFAULT_DOF_FOCAL_RANGE,
            .bokeh_scale = DEFAULT_DOF_BOKEH_SCALE}};

static const PostProcessPreset PRESET_VINTAGE = {
    .active_effects =
        (unsigned int)POSTFX_VIGNETTE | (unsigned int)POSTFX_GRAIN |
        (unsigned int)POSTFX_CHROM_ABBR | (unsigned int)POSTFX_EXPOSURE |
        (unsigned int)POSTFX_COLOR_GRADING,
    .vignette = {.intensity = 0.7F, .extent = 0.5F},
    .grain = {.intensity = 0.06F,
              .intensity_shadows = 1.5F,
              .intensity_midtones = 1.0F,
              .intensity_highlights = 0.5F,
              .shadows_max = 0.15F,
              .highlights_min = 0.6F,
              .texel_size = 1.5F},
    .exposure = {.exposure = 0.9F},
    .chrom_abbr = {.strength = 0.02F},
    .white_balance = {.temperature = 5500.0F, .tint = 0.05F},
    .color_grading = {.saturation = 0.8F,
                      .contrast = 1.0F,
                      .gamma = 1.0F,
                      .gain = 1.0F,
                      .offset = 0.0F},
    .tonemapper = {.slope = DEFAULT_FILMIC_SLOPE,
                   .toe = DEFAULT_FILMIC_TOE,
                   .shoulder = DEFAULT_FILMIC_SHOULDER,
                   .black_clip = DEFAULT_FILMIC_BLACK_CLIP,
                   .white_clip = DEFAULT_FILMIC_WHITE_CLIP},
    .bloom = {.intensity = 0.0F,
              .threshold = 1.0F,
              .soft_threshold = 0.5F,
              .radius = 1.0F},
    .dof = {.focal_distance = DEFAULT_DOF_FOCAL_DISTANCE,
            .focal_range = DEFAULT_DOF_FOCAL_RANGE,
            .bokeh_scale = DEFAULT_DOF_BOKEH_SCALE}};

static const PostProcessPreset PRESET_MATRIX = {
    .active_effects =
        (unsigned int)POSTFX_COLOR_GRADING | (unsigned int)POSTFX_BLOOM,
    .vignette = {.intensity = DEFAULT_VIGNETTE_INTENSITY,
                 .extent = DEFAULT_VIGNETTE_EXTENT},
    .grain = {.intensity = DEFAULT_GRAIN_INTENSITY,
              .intensity_shadows = 1.0F,
              .intensity_midtones = 1.0F,
              .intensity_highlights = 1.0F,
              .shadows_max = 0.09F,
              .highlights_min = 0.5F,
              .texel_size = 1.0F},
    .exposure = {.exposure = DEFAULT_EXPOSURE},
    .chrom_abbr = {.strength = DEFAULT_CHROM_ABBR_STRENGTH},
    .white_balance = {.temperature = 7500.0F, .tint = 0.2F},
    .color_grading = {.saturation = 0.5F,
                      .contrast = 1.2F,
                      .gamma = 0.9F,
                      .gain = 1.1F,
                      .offset = 0.02F},
    .tonemapper = {.slope = DEFAULT_FILMIC_SLOPE,
                   .toe = DEFAULT_FILMIC_TOE,
                   .shoulder = DEFAULT_FILMIC_SHOULDER,
                   .black_clip = DEFAULT_FILMIC_BLACK_CLIP,
                   .white_clip = DEFAULT_FILMIC_WHITE_CLIP},
    .bloom = {.intensity = 0.2F,
              .threshold = 0.8F,
              .soft_threshold = 0.5F,
              .radius = 1.0F},
    .dof = {.focal_distance = DEFAULT_DOF_FOCAL_DISTANCE,
            .focal_range = DEFAULT_DOF_FOCAL_RANGE,
            .bokeh_scale = DEFAULT_DOF_BOKEH_SCALE}};

static const PostProcessPreset PRESET_BW_CONTRAST = {
    .active_effects = (unsigned int)POSTFX_COLOR_GRADING,
    .vignette = {.intensity = DEFAULT_VIGNETTE_INTENSITY,
                 .extent = DEFAULT_VIGNETTE_EXTENT},
    .grain = {.intensity = DEFAULT_GRAIN_INTENSITY,
              .intensity_shadows = 1.0F,
              .intensity_midtones = 1.0F,
              .intensity_highlights = 1.0F,
              .shadows_max = 0.09F,
              .highlights_min = 0.5F,
              .texel_size = 1.0F},
    .exposure = {.exposure = DEFAULT_EXPOSURE},
    .chrom_abbr = {.strength = DEFAULT_CHROM_ABBR_STRENGTH},
    .white_balance = {.temperature = DEFAULT_WB_TEMP, .tint = DEFAULT_WB_TINT},
    .color_grading = {.saturation = 0.0F,
                      .contrast = 1.5F,
                      .gamma = 1.0F,
                      .gain = 1.0F,
                      .offset = 0.0F},
    .tonemapper = {.slope = DEFAULT_FILMIC_SLOPE,
                   .toe = DEFAULT_FILMIC_TOE,
                   .shoulder = DEFAULT_FILMIC_SHOULDER,
                   .black_clip = DEFAULT_FILMIC_BLACK_CLIP,
                   .white_clip = DEFAULT_FILMIC_WHITE_CLIP},
    .bloom = {.intensity = 0.0F,
              .threshold = 1.0F,
              .soft_threshold = 0.5F,
              .radius = 1.0F},
    .dof = {.focal_distance = DEFAULT_DOF_FOCAL_DISTANCE,
            .focal_range = DEFAULT_DOF_FOCAL_RANGE,
            .bokeh_scale = DEFAULT_DOF_BOKEH_SCALE}};

#endif /* POSTPROCESS_PRESETS_H */
