name: Publish Docs

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - ".github/workflows/docs.yml"

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0 # fetching all history is often better for git-revision-date plugins

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v6
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - uses: actions/cache@v5
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz libpango-1.0-0 libharfbuzz0b libpangoft2-1.0-0

      - name: Install Python Dependencies
        run: pip install -r requirements-dev.txt

      - name: Build Documentation
        env:
          ENABLE_PDF: 1
        run: |
          mkdocs build
          doxygen Doxyfile (cd site/doxygen && ln -s html/index.html index.html) || true

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site
          branch: gh-pages
